import { useEffect, useRef } from 'react';
import { AlertTriangle, Info, Mic, VideoOff } from 'lucide-react';
import { Portrait } from './ui';

// The label stays white for contrast; only the icon carries the colour.
const STATUS = {
  speaking: { label: 'Speaking', iconClass: 'text-accent' },
  listening: { label: 'Listening', iconClass: 'text-good' },
  thinking: { label: 'Thinking', iconClass: 'text-white/70' },
};

function StatusPill({ state }) {
  const status = STATUS[state];
  if (!status) return null;
  return (
    <span className="inline-flex items-center gap-2 rounded-full bg-black/60 px-3 py-1 text-xs font-medium text-white backdrop-blur">
      {state === 'speaking' && (
        <span className={`voice-bars flex h-3.5 items-center gap-[3px] ${status.iconClass}`} aria-hidden><span /><span /><span /><span /></span>
      )}
      {state === 'listening' && <Mic className={`size-3.5 ${status.iconClass}`} aria-hidden />}
      {state === 'thinking' && <span className={`flex gap-1 ${status.iconClass}`} aria-hidden>{[0, 1, 2].map((i) => <span key={i} className="size-1 animate-pulse rounded-full bg-current" style={{ animationDelay: `${i * 0.2}s` }} />)}</span>}
      {status.label}
    </span>
  );
}

// The interviewer is a still photo with speaking cues and a browser voice, and says so.
// A lip-synced video avatar provider could replace <Portrait> here (see README).
export function InterviewerTile({ person, state, size = 'large' }) {
  const large = size === 'large';
  const motion = state === 'speaking' ? 'animate-talk' : 'animate-breathe';
  return (
    <div
      className={`relative overflow-hidden rounded-2xl border bg-surface transition-[border-color,box-shadow] duration-300 ${
        state === 'speaking' ? 'border-accent/70 shadow-[0_0_0_1px_rgba(57,135,229,0.35)]' : 'border-line'
      } ${large ? 'h-full' : 'aspect-video w-44 shrink-0 lg:w-full'}`}
    >
      <div className={`absolute inset-0 ${motion}`}>
        <Portrait avatar={person.avatar} className="size-full [&>img]:object-top" initialsClassName={large ? 'text-6xl' : 'text-xl'} />
      </div>
      <div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-black/75 to-transparent" />

      <div className="absolute left-3 top-3"><StatusPill state={state} /></div>
      {large && (
        <span
          className="absolute right-3 top-3 inline-flex items-center gap-1.5 rounded-full bg-black/45 px-2.5 py-1 text-[11px] text-white/70 backdrop-blur"
          title="A still photo with animated speaking cues. The voice is generated by your browser."
        >
          <Info className="size-3" aria-hidden /> Photo avatar · synthetic voice
        </span>
      )}

      <div className={`absolute bottom-0 left-0 ${large ? 'p-4' : 'p-2.5'}`}>
        <p className={`font-medium text-white ${large ? 'text-base' : 'text-xs'}`}>{person.name}</p>
        <p className={`text-white/65 ${large ? 'text-sm' : 'text-[11px]'}`}>{person.title}</p>
      </div>
    </div>
  );
}

// Shown on the self-view in a proctored interview; a healthy check stays quiet.
const FACE_CHIP = {
  loading: { label: 'Starting checks…', warn: false },
  no_face: { label: 'Face not visible', warn: true },
  looking_away: { label: 'Looking away', warn: true },
  multiple_faces: { label: 'Another person in view', warn: true },
  no_camera: { label: 'Camera off', warn: true },
};

export function CandidateTile({ stream, listening, name, cameraError, videoRef, faceStatus }) {
  const ownRef = useRef(null);
  const video = videoRef || ownRef;
  useEffect(() => {
    if (video.current) video.current.srcObject = stream;
  }, [stream, video]);
  const chip = faceStatus && FACE_CHIP[faceStatus];

  return (
    <div className={`relative aspect-video w-44 shrink-0 overflow-hidden rounded-2xl border bg-raised lg:w-full ${listening ? 'border-good/60' : 'border-line'}`}>
      {stream ? (
        <video ref={video} autoPlay muted playsInline className="size-full -scale-x-100 object-cover" />
      ) : (
        <div className="grid size-full place-items-center">
          <div className="text-center">
            <span className="mx-auto grid size-9 place-items-center rounded-full bg-line text-sm font-semibold text-ink-soft lg:size-12 lg:text-base">
              {(name || 'You').slice(0, 1).toUpperCase()}
            </span>
            <p className="mt-2 hidden items-center justify-center gap-1 text-[11px] text-muted lg:flex">
              <VideoOff className="size-3" aria-hidden /> {cameraError || 'Camera off'}
            </p>
          </div>
        </div>
      )}
      {chip && (
        <span className="absolute left-2 top-2 inline-flex items-center gap-1 rounded-full bg-black/65 px-2 py-0.5 text-[10px] font-medium text-white backdrop-blur">
          {chip.warn && <AlertTriangle className="size-3 text-warning" aria-hidden />} {chip.label}
        </span>
      )}
      <div className="absolute bottom-0 left-0 flex items-center gap-1.5 p-2.5">
        {listening && <Mic className="size-3.5 text-good" aria-label="Microphone on" />}
        <span className="text-xs font-medium text-white">You</span>
      </div>
    </div>
  );
}
